In [1]:
import pickle 
from torchkge.data_structures import KnowledgeGraph
import pandas as pd

transE_triplet = pickle.load(open('results/transE/Triplet_Classification.pkl', 'rb'))
transE_link = pickle.load(open('results/transE/Link_Prediction.pkl', 'rb'))
transE_relation = pickle.load(open('results/transE/Relation_Prediction.pkl', 'rb'))


bilinear_triplet = pickle.load(open('results/bilinear/Triplet_Classification.pkl', 'rb'))
bilinear_link = pickle.load(open('results/bilinear/Link_Prediction.pkl', 'rb'))
bilinear_relation = pickle.load(open('results/bilinear/Relation_Prediction.pkl', 'rb'))

deep_triplet = pickle.load(open('results/deep/Triplet_Classification.pkl', 'rb'))
deep_link = pickle.load(open('results/deep/Link_Prediction.pkl', 'rb'))
deep_relation = pickle.load(open('results/deep/Relation_Prediction.pkl', 'rb'))

input_df = pickle.load(open('results/data/model_input_df.pkl','rb'))

C:\Users\debor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [29]:
input_df.style
input_df.to_csv('data/input_df.csv')

In [3]:
def get_id(kg):
    id = "id not found"
    kg_list = kg.get_df().values.tolist()
    for i, x in enumerate(kg_list):
        if "Archivnummer" in x:
            id = kg_list[i][1]
    return id

In [77]:
#transE = pickle.load(open('results/transE/Triplet_Classification.pkl', 'rb'))
top1, top2, top3, top4, top5, top6, top7, top8, top9, top10 = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
id1, id2, id3, id4, id5, id6, id7, id8, id9, id10 = "","","","","","","","","",""

for res,kg in deep_triplet: #change model name if needed: transE_triplet / bilinear_triplet / deep_triplet
    if res > top1:
        top1 = res
        id1 = get_id(kg)
        kg1 = kg
    elif res > top2:
        top2 = res
        id2 = get_id(kg)
        kg2 = kg
    elif res > top3:
        top3 = res
        id3 = get_id(kg)
        kg3 = kg
    elif res > top4:
        top4 = res
        id4 = get_id(kg)
        kg4 = kg
    elif res > top5:
        top5 = res
        id5 = get_id(kg)
        kg5 = kg
    elif res > top6:
        top6 = res
        id6 = get_id(kg)
        kg6 = kg
    elif res > top7:
        top7 = res
        id7 = get_id(kg)
        kg7 = kg
    elif res > top8:
        top8 = res
        id8 = get_id(kg)
        kg8 = kg
    elif res > top9:
        top9 = res
        id9 = get_id(kg)
        kg9 = kg
    elif res > top10:
        top10 = res
        id10 = get_id(kg)
        kg10 = kg

print("top 1: ",top1, " Archivnummer: ", id1)
print("top 2: ",top2, " Archivnummer: ", id2)
print("top 3: ",top3, " Archivnummer: ", id3)
print("top 4: ",top4, " Archivnummer: ", id4)
print("top 5: ",top5, " Archivnummer: ", id5)
print("top 6: ",top6, " Archivnummer: ", id6)
print("top 7: ",top7, " Archivnummer: ", id7)
print("top 8: ",top8, " Archivnummer: ", id8)
print("top 9: ",top9, " Archivnummer: ", id9)
print("top 10: ",top10, " Archivnummer: ", id10)

pickle.dump([[top1,id1],[top2,id2],[top3,id3],[top4,id4],[top5,id5],[top6,id6],[top7,id7],[top8,id8],[top9,id9], [top10, id10]], open("results/deep/top3/triplet.pkl","wb"))
#pickle.dump([[top1,id1],[top2,id2],[top3,id3],[top4,id4],[top5,id5],[top6,id6],[top7,id7],[top8,id8],[top9,id9], [top10, id10]], open("results/transE/top3/triplet.pkl","wb"))
#pickle.dump([[top1,id1],[top2,id2],[top3,id3],[top4,id4],[top5,id5],[top6,id6],[top7,id7],[top8,id8],[top9,id9], [top10, id10]], open("results/bilinear/top3/triplet.pkl","wb"))

top 1:  0.5714285714285714  Archivnummer:  003650
top 2:  0.5327868852459017  Archivnummer:  005710
top 3:  0.5294117647058824  Archivnummer:  005638A
top 4:  0.5255591054313099  Archivnummer:  006567
top 5:  0.5238095238095238  Archivnummer:  003649
top 6:  0.5200892857142857  Archivnummer:  004119
top 7:  0.5163398692810458  Archivnummer:  006108
top 8:  0.5144927536231884  Archivnummer:  004299
top 9:  0.5128205128205128  Archivnummer:  004075B
top 10:  0.5123456790123457  Archivnummer:  005746

In [69]:
#transE = pickle.load(open('results/transE/Link_Prediction.pkl', 'rb'))
#bilinear = pickle.load(open('results/bilinear/Link_Prediction.pkl', 'rb'))
#deep = pickle.load(open('results/deep/Link_Prediction.pkl', 'rb'))

In [89]:
top1mean,top2mean,top3mean, top4mean,top5mean,top6mean, top7mean,top8mean,top9mean, top10mean = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
id1mean,id2mean,id3mean, id4mean,id5mean,id6mean, id7mean,id8mean,id9mean, id10mean = "","","","","","","","","",""
top1hit,top2hit,top3hit, top4hit,top5hit,top6hit, top7hit,top8hit,top9hit, top10hit= 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
id1hit,id2hit,id3hit, id4hit,id5hit,id6hit, id7hit,id8hit,id9hit, id10hit= "","","","","","","","","",""
top1mrr,top2mrr,top3mrr, top4mrr,top5mrr,top6mrr, top7mrr,top8mrr,top9mrr, top10mrr= 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
id1mrr,id2mrr,id3mrr, id4mrr,id5mrr,id6mrr, id7mrr,id8mrr,id9mrr, id10mrr= "","","","","","","","","",""

for x in transE_relation: #change model name if needed: transE_relation / bilinear_relation / deep_relation
    #print(len(x))
    mean = x[0][0][0]
    hit = x[0][1][0]
    mrr = x[0][2][0]
    id = get_id(x[1])

    if mean > top1mean:
        top1mean = mean
        id1mean = id
    elif mean > top2mean:
        top2mean = mean
        id2mean = id
    elif mean > top3mean:
        top3mean = mean
        id3mean = id    
    elif mean > top4mean:
        top4mean = mean
        id4mean = id
    elif mean > top5mean:
        top5mean = mean
        id5mean = id
    elif mean > top6mean:
        top6mean = mean
        id6mean = id
    elif mean > top7mean:
        top7mean = mean
        id7mean = id    
    elif mean > top8mean:
        top8mean = mean
        id8mean = id
    elif mean > top9mean:
        top9mean = mean
        id9mean = id
    elif mean > top10mean:
        top10mean = mean
        id10mean = id

    if hit > top1hit:
        top1hit = hit
        id1hit = id
        kg1 = x[1].get_df()
    elif hit > top2hit:
        top2hit = hit
        id2hit = id
        kg2 = x[1].get_df()
    elif hit > top3hit:
        top3hit = hit
        id3hit = id
        kg3 = x[1].get_df()
    elif hit > top4hit:
        top4hit = hit
        id4hit = id
        kg4 = x[1].get_df()
    elif hit > top5hit:
        top5hit = hit
        id5hit = id
        kg5 = x[1].get_df()
    elif hit > top6hit:
        top6hit = hit
        id6hit = id
        kg6 = x[1].get_df()
    elif hit > top7hit:
        top7hit = hit
        id7hit = id
        kg7 = x[1].get_df()
    elif hit > top8hit:
        top8hit = hit
        id8hit = id
        kg8 = x[1].get_df()
    elif hit > top9hit:
        top9hit = hit
        id9hit = id
        kg9 = x[1].get_df()
    elif hit > top10hit:
        top10hit = hit
        id10hit = id
        kg10 = x[1].get_df()

    if mrr > top1mrr:
        top1mrr = mrr
        id1mrr = id
    elif mrr > top2mrr:
        top2mrr = mrr
        id2mrr = id
    elif mrr > top3mrr:
        top3mrr = mrr
        id3mrr = id
    elif mrr > top4mrr:
        top4mrr = mrr
        id4mrr = id
    elif mrr > top5mrr:
        top5mrr = mrr
        id5mrr = id
    elif mrr > top6mrr:
        top6mrr = mrr
        id6mrr = id
    elif mrr > top7mrr:
        top7mrr = mrr
        id7mrr = id
    elif mrr > top8mrr:
        top8mrr = mrr
        id8mrr = id
    elif mrr > top9mrr:
        top9mrr = mrr
        id9mrr = id
    elif mrr > top10mrr:
        top10mrr = mrr
        id10mrr = id

    #print("mean: ", (x[0][0][0]), "hit: ", (x[0][1][0]), "mrr: ", (x[0][2][0]))
    #print(get_id(x[1]))


#pickle.dump([[top1mean,id1mean],[top2mean,id2mean],[top3mean,id3mean]], open("results/transE/top3/link_mean.pkl","wb"))
pickle.dump([[top1hit,id1hit],[top2hit,id2hit],[top3hit,id3hit]], open("results/transE/top3/relation_hit.pkl", "wb"))
#pickle.dump([[top1mrr,id1mrr],[top2mrr,id2mrr],[top3mrr,id3mrr]], open("results/transE/top3/link_mrr.pkl","wb"))

In [90]:
print("top 1 (mrr): ",top1mrr, " Archivnummer: ", id1mrr)
print("top 2 (mrr): ",top2mrr, " Archivnummer: ", id2mrr)
print("top 3 (mrr): ",top3mrr, " Archivnummer: ", id3mrr)
print("top 4 (mrr): ",top4mrr, " Archivnummer: ", id4mrr)
print("top 5 (mrr): ",top5mrr, " Archivnummer: ", id5mrr)
print("top 6 (mrr): ",top6mrr, " Archivnummer: ", id6mrr)
print("top 7 (mrr): ",top7mrr, " Archivnummer: ", id7mrr)
print("top 8 (mrr): ",top8mrr, " Archivnummer: ", id8mrr)
print("top 9 (mrr): ",top9mrr, " Archivnummer: ", id9mrr)
print("top 10 (mrr): ",top10mrr, " Archivnummer: ", id10mrr, "\n")

print("top 1 (mean): ",top1mean, " Archivnummer: ", id1mean)
print("top 2 (mean): ",top2mean, " Archivnummer: ", id2mean)
print("top 3 (mean): ",top3mean, " Archivnummer: ", id3mean)
print("top 4 (mean): ",top4mean, " Archivnummer: ", id4mean)
print("top 5 (mean): ",top5mean, " Archivnummer: ", id5mean)
print("top 6 (mean): ",top6mean, " Archivnummer: ", id6mean)
print("top 7 (mean): ",top7mean, " Archivnummer: ", id7mean)
print("top 8 (mean): ",top8mean, " Archivnummer: ", id8mean)
print("top 9 (mean): ",top9mean, " Archivnummer: ", id9mean)
print("top 10 (mean): ",top10mean, " Archivnummer: ", id10mean, "\n")

print("top 1 (hit): ",top1hit, " Archivnummer: ", id1hit)
print("top 2 (hit): ",top2hit, " Archivnummer: ", id2hit)
print("top 3 (hit): ",top3hit, " Archivnummer: ", id3hit)
print("top 4 (hit): ",top4hit, " Archivnummer: ", id4hit)
print("top 5 (hit): ",top5hit, " Archivnummer: ", id5hit)
print("top 6 (hit): ",top6hit, " Archivnummer: ", id6hit)
print("top 7 (hit): ",top7hit, " Archivnummer: ", id7hit)
print("top 8 (hit): ",top8hit, " Archivnummer: ", id8hit)
print("top 9 (hit): ",top9hit, " Archivnummer: ", id9hit)
print("top 10 (hit): ",top10hit, " Archivnummer: ", id10hit, "\n")

top 1 (mrr):  0.6842105388641357  Archivnummer:  004806
top 2 (mrr):  0.5263158082962036  Archivnummer:  000100
top 3 (mrr):  0.5263158082962036  Archivnummer:  000104
top 4 (mrr):  0.5263158082962036  Archivnummer:  000106
top 5 (mrr):  0.5263158082962036  Archivnummer:  000110
top 6 (mrr):  0.5263158082962036  Archivnummer:  000113
top 7 (mrr):  0.5263158082962036  Archivnummer:  000115
top 8 (mrr):  0.5263158082962036  Archivnummer:  000116
top 9 (mrr):  0.5263158082962036  Archivnummer:  000118
top 10 (mrr):  0.5263158082962036  Archivnummer:  000120

top 1 (mean):  22.0  Archivnummer:  000001A
top 2 (mean):  22.0  Archivnummer:  000068a
top 3 (mean):  18.674419403076172  Archivnummer:  001339
top 4 (mean):  18.571428298950195  Archivnummer:  004279
top 5 (mean):  18.571428298950195  Archivnummer:  004281
top 6 (mean):  17.85714340209961  Archivnummer:  004790
top 7 (mean):  17.799999237060547  Archivnummer:  004232
top 8 (mean):  17.44444465637207  Archivnummer:  005641A
top 9 (mean):  17.285715103149414  Archivnummer:  004223
top 10 (mean):  17.238094329833984  Archivnummer:  005950

top 1 (hit):  0.9230769276618958  Archivnummer:  005683
top 2 (hit):  0.8918918967247009  Archivnummer:  003378
top 3 (hit):  0.8888888955116272  Archivnummer:  005663A
top 4 (hit):  0.8181818127632141  Archivnummer:  002146
top 5 (hit):  0.8100000023841858  Archivnummer:  004852
top 6 (hit):  0.8064516186714172  Archivnummer:  005810
top 7 (hit):  0.8035714030265808  Archivnummer:  006755
top 8 (hit):  0.7777777910232544  Archivnummer:  005643B
top 9 (hit):  0.7596153616905212  Archivnummer:  006696
top 10 (hit):  0.75  Archivnummer:  003937C

In [49]:
def get_different_rows(source_df, new_df):
    merged_df = source_df.merge(new_df, indicator=True, how='outer')
    changed_rows_df = merged_df[merged_df['_merge'] == 'right_only']
    return changed_rows_df.drop('_merge', axis=1)
def get_same_rows(source_df, new_df):
    merged_df = pd.merge(source_df, new_df, on=['from','to', 'rel'], how='inner')  #change on if needed  
    return merged_df

In [101]:
diff = get_same_rows(input_df, kg10)
diff.style
#kg7.get_df().style